spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: 8081
  servlet:
    context-path: /

jwt:
  secret: my-super-secret-key-that-must-be-at-least-256-bits-long-for-HS256-algorithm
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    export:
      prometheus:
        enabled: true

