spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

jwt:
  secret: my-super-secret-key-that-must-be-at-least-256-bits-long-for-HS256-algorithm

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    export:
      prometheus:
        enabled: true

